import { Geist, Geist_Mono, Montserrat, Lato } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/mode-toggle/theme-provider"

const montserrat = Montserrat({
  weight: ['400', '600', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
});

const lato = Lato({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export function Header1() {
  return <h1 className={montserrat.className}>Title 1</h1>;
}

export function Header2() {
  return <h2 className={montserrat.className}>Title 2</h2>;
}

export function Header3() {
  return <h3 className={montserrat.className}>Title 3</h3>;
}

export function Paragraph({ children }) {
  return <p className={lato.className}>{children}</p>;
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className={lato.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
